language: node_js
node_js: ["0.10"]

language: ruby
rvm:
  - 2.0.0
  - 1.9.3

notifications:
  email:
    recipients:
     - dropbox+travis@ricostacruz.com
    on_success: change
    on_failure: change
